import type { DBSchema } from 'idb';

export type OAuthProvider = 'google' | 'github';
export type EnergyLevel = 'low' | 'medium' | 'high';
export type EntityType = 'item' | 'routine' | 'person' | 'workContext';
export type OpType = 'create' | 'update' | 'delete';

export interface StoredAccount {
    id: string; // Better Auth user ID (UUID)
    email: string;
    name: string;
    image: string | null; // null (not undefined) to satisfy exactOptionalPropertyTypes
    provider: OAuthProvider; // last provider used to sign in to this account
    addedAt: number; // unix ms — used to preserve order in the switcher
}

export interface StoredItem {
    _id: string; // client-generated UUID — doubles as the MongoDB _id
    userId: string; // Better Auth user ID — mirrors ItemInterface.user
    status: 'inbox' | 'nextAction' | 'calendar' | 'waitingFor' | 'done' | 'trash';
    title: string;
    createdTs: string;
    updatedTs: string; // ISO datetime — last-write-wins conflict resolution anchor
    workContextIds?: string[]; // refs to StoredWorkContext._id
    peopleIds?: string[]; // refs to StoredPerson._id
    waitingForPersonId?: string; // ref to StoredPerson._id — the person being waited on
    expectedBy?: string; // ISO date — deadline
    ignoreBefore?: string; // ISO date — tickler: item hidden until this date passes
    timeStart?: string; // ISO datetime — calendar items only
    timeEnd?: string; // ISO datetime — calendar items only
    calendarEventId?: string;
    calendarIntegrationId?: string;
    routineId?: string; // ref to StoredRoutine._id — set if generated by a routine
    energy?: EnergyLevel;
    time?: number; // minutes
    focus?: boolean;
    urgent?: boolean;
    notes?: string; // freeform markdown notes — applies to all statuses
}

export interface StoredRoutineTemplate {
    workContextIds?: string[];
    peopleIds?: string[];
    energy?: EnergyLevel;
    time?: number;
    focus?: boolean;
    urgent?: boolean;
    /** Days before expectedBy to set ignoreBefore (tickler). undefined = no tickler; 0 = show on due date. */
    ticklerLeadDays?: number;
    notes?: string;
}

export interface StoredRoutine {
    _id: string;
    userId: string;
    title: string;
    /**
     * nextAction: next instance created after previous is done/trashed (after-completion trigger).
     * calendar: next instance created on a fixed rrule schedule.
     */
    routineType: 'nextAction' | 'calendar';
    /** RFC 5545 RRULE string. Required for all routines. */
    rrule: string;
    /** @deprecated Use routineType instead. */
    triggerMode?: 'afterCompletion' | 'fixedSchedule';
    /** @deprecated Use rrule instead. */
    afterCompletionDelayDays?: number;
    calendarEventId?: string;
    calendarIntegrationId?: string;
    template: StoredRoutineTemplate;
    active: boolean;
    createdTs: string;
    updatedTs: string;
    /** Present when routineType === 'calendar'. Defines time and duration for generated calendar items. */
    calendarItemTemplate?: {
        timeOfDay: string; // HH:MM (24h) — start time
        duration: number; // minutes
    };
    /** ISO date of the most recently generated calendar item. Used to avoid scanning items for the next occurrence. */
    lastGeneratedDate?: string;
    /** Exception dates in the rrule series. 'skipped' when trashed; 'modified' when GCal moves the occurrence. */
    routineExceptions?: Array<{
        date: string; // ISO date of the original rrule occurrence
        type: 'skipped' | 'modified';
        itemId?: string;
        newTimeStart?: string; // ISO datetime — present when type === 'modified'
        newTimeEnd?: string;
    }>;
}

export interface StoredPerson {
    _id: string;
    userId: string;
    name: string;
    email?: string;
    phone?: string;
    externalCalendarId?: string;
    notes?: string;
    createdTs: string;
    updatedTs: string;
}

export interface StoredWorkContext {
    _id: string;
    userId: string;
    name: string; // e.g. "near a phone", "at work", "with family"
    createdTs: string;
    updatedTs: string;
}

export type StoredEntity = StoredItem | StoredRoutine | StoredPerson | StoredWorkContext;

export interface StoredDeviceSyncState {
    _id: 'local'; // singleton — only one entry per device
    deviceId: string; // stable UUID generated on first launch; sent with every push/pull request
    lastSyncedTs: string; // ISO datetime of the last successful pull from the server
}

export interface SyncOperation {
    id?: number; // auto-increment — omitted before insertion
    entityType: EntityType;
    entityId: string;
    opType: OpType;
    queuedAt: string; // ISO datetime — determines replay order when multiple ops are queued offline
    /**
     * Full entity state at the time of the operation. null for delete operations.
     * Stored as a snapshot (not a diff) so last-write-wins resolution is trivial on the server.
     */
    snapshot: StoredEntity | null;
}

export interface MyDB extends DBSchema {
    // All known accounts across all sign-ins
    accounts: {
        key: string; // StoredAccount.id
        value: StoredAccount;
        indexes: { email: string };
    };
    // Single-entry store: which account is currently active (matches the live Better Auth session)
    activeAccount: {
        key: 'active';
        value: { userId: string };
    };
    // All GTD items for all accounts on this device
    items: {
        key: string; // StoredItem._id
        value: StoredItem;
        indexes: { userId: string };
    };
    // Recurring task definitions
    routines: {
        key: string; // StoredRoutine._id
        value: StoredRoutine;
        indexes: { userId: string };
    };
    // Named people referenced in items and waitingFor
    people: {
        key: string; // StoredPerson._id
        value: StoredPerson;
        indexes: { userId: string };
    };
    // Named work contexts used to tag and filter nextAction items
    workContexts: {
        key: string; // StoredWorkContext._id
        value: StoredWorkContext;
        indexes: { userId: string };
    };
    // Pending mutations to replay against the server when connectivity is restored
    syncOperations: {
        key: number; // auto-increment
        value: SyncOperation;
    };
    // Per-device sync cursor — singleton keyed by 'local'
    deviceSyncState: {
        key: 'local';
        value: StoredDeviceSyncState;
    };
}
