import type { DBSchema } from 'idb';

export type OAuthProvider = 'google' | 'github';
export type EnergyLevel = 'low' | 'medium' | 'high';
export type EntityType = 'item' | 'routine' | 'person' | 'workContext';
export type OpType = 'create' | 'update' | 'delete' | 'rsvp';

/** Mirrored from api-server/src/types/entities.ts. Keep in sync. */
export interface GCalPerson {
    email: string;
    displayName?: string;
    self?: boolean;
}
export type GCalResponseStatus = 'needsAction' | 'accepted' | 'declined' | 'tentative';
export interface GCalAttendee extends GCalPerson {
    responseStatus: GCalResponseStatus;
    organizer?: boolean;
    optional?: boolean;
}
// Mirrors `GCalEventType` in api-server/src/types/entities.ts — `fromGmail` is Google's value
// for events auto-created from Gmail attachments. Keep in lockstep with the server.
export type GCalEventType = 'default' | 'outOfOffice' | 'focusTime' | 'workingLocation' | 'fromGmail';

export interface StoredAccount {
    id: string; // Better Auth user ID (UUID)
    email: string;
    name: string;
    image: string | null; // null (not undefined) to satisfy exactOptionalPropertyTypes
    provider: OAuthProvider; // last provider used to sign in to this account
    addedAt: number; // unix ms — used to preserve order in the switcher
}

export interface StoredItem {
    _id: string; // client-generated UUID — doubles as the MongoDB _id
    userId: string; // Better Auth user ID — mirrors ItemInterface.user
    status: 'inbox' | 'nextAction' | 'calendar' | 'waitingFor' | 'somedayMaybe' | 'done' | 'trash';
    title: string;
    createdTs: string;
    updatedTs: string; // ISO datetime — last-write-wins conflict resolution anchor
    workContextIds?: string[]; // refs to StoredWorkContext._id
    peopleIds?: string[]; // refs to StoredPerson._id
    waitingForPersonId?: string; // ref to StoredPerson._id — the person being waited on
    expectedBy?: string; // ISO date — deadline
    ignoreBefore?: string; // ISO date — tickler: item hidden until this date passes
    timeStart?: string; // ISO datetime for timed events, YYYY-MM-DD when allDay — calendar items only
    timeEnd?: string; // ISO datetime for timed events, YYYY-MM-DD (exclusive) when allDay — calendar items only
    allDay?: boolean; // true when timeStart/timeEnd are date-only YYYY-MM-DD strings (GCal exclusive-end preserved)
    calendarEventId?: string;
    calendarIntegrationId?: string;
    calendarSyncConfigId?: string; // ref to StoredCalendarSyncConfig._id — tracks which calendar this event belongs to
    // Set by the disconnect-with-keep path so a later reconnect can do a strong-key relink without
    // the live calendar* fields. Cleared as soon as relink restores those live fields.
    lastKnownCalendarEventId?: string;
    lastKnownCalendarIntegrationId?: string;
    lastKnownCalendarSyncConfigId?: string;
    // Origin Google account email of the markers — lets the server tell a same-account reconnect
    // (rewrite the markers) from a different-account one (wipe). Round-trips through sync untouched.
    lastKnownCalendarAccountEmail?: string;
    // Set on routine-generated calendar items so exception sync can locate them by GCal instance id
    // even after `timeStart` has been shifted by a prior exception. Format: `<masterEventId>_<YYYYMMDDTHHMMSSZ>`.
    calendarInstanceEventId?: string;
    lastPushedToGCalTs?: string; // ISO datetime — echo detection: prevents re-importing changes the app just pushed
    lastSyncedFromGCalTs?: string; // ISO datetime — event.updated of the last inbound GCal payload applied; conflict anchor for inbound updates (independent of local-write updatedTs)
    routineId?: string; // ref to StoredRoutine._id — set if generated by a routine
    energy?: EnergyLevel;
    time?: number; // minutes
    focus?: boolean; // on the current-focus shortlist (Nirvana-style Focus list) — floats the item to the top of Next Actions
    urgent?: boolean;
    notes?: string; // freeform markdown notes — applies to all statuses
    lastSyncedNotes?: string; // last notes value synced from/to Google Calendar — used for conflict detection
    /** GCal-mirror fields. Server-overwritten on every inbound pull; RSVP + attendee-editor are local-write exceptions. */
    organizer?: GCalPerson;
    creator?: GCalPerson;
    attendees?: GCalAttendee[]; // sorted by email
    responseStatus?: GCalResponseStatus; // denormalized from self attendee
    eventType?: GCalEventType;
    meetingLink?: string; // Meet/Zoom join URL — read-only, GCal-owned
    location?: string; // physical / free-text location — read-only, GCal-owned
    htmlLink?: string; // canonical Google Calendar event URL — read-only, GCal-owned
    cancelledByGCal?: boolean; // true when an inbound GCal cancel pushed this item to trash
}

export interface StoredRoutineTemplate {
    workContextIds?: string[];
    peopleIds?: string[];
    energy?: EnergyLevel;
    time?: number;
    focus?: boolean; // generated items start on the current-focus shortlist (floats to the top of Next Actions)
    urgent?: boolean;
    notes?: string;
}

export interface StoredRoutine {
    _id: string;
    userId: string;
    title: string;
    /**
     * nextAction: next instance created after previous is done/trashed (after-completion trigger).
     * calendar: next instance created on a fixed rrule schedule.
     */
    routineType: 'nextAction' | 'calendar';
    /** RFC 5545 RRULE string. Required for all routines. */
    rrule: string;
    /** @deprecated Use routineType instead. */
    triggerMode?: 'afterCompletion' | 'fixedSchedule';
    /** @deprecated Use rrule instead. */
    afterCompletionDelayDays?: number;
    calendarEventId?: string;
    calendarIntegrationId?: string;
    calendarSyncConfigId?: string;
    // Set by the disconnect-with-keep path so a later reconnect can do a strong-key relink without
    // the live calendar* fields. Cleared as soon as relink restores those live fields.
    lastKnownCalendarEventId?: string;
    lastKnownCalendarIntegrationId?: string;
    lastKnownCalendarSyncConfigId?: string;
    // Origin Google account email of the markers — lets the server tell a same-account reconnect
    // (rewrite the markers) from a different-account one (wipe). Round-trips through sync untouched.
    lastKnownCalendarAccountEmail?: string;
    /** Ref to the routine this was split from ("this and all following" edit). */
    splitFromRoutineId?: string;
    /** Raw GCal rebased-master id (`<bareId>_R<anchor>`) for split-successor routines — see RoutineInterface. */
    calendarRebasedEventId?: string;
    lastPushedToGCalTs?: string;
    lastSyncedNotes?: string; // last template.notes value synced from/to Google Calendar — used for conflict detection
    /** GCal master organizer/creator/attendees/responseStatus/eventType — RFC 5545 mirror; see RoutineInterface for semantics. */
    organizer?: GCalPerson;
    creator?: GCalPerson;
    attendees?: GCalAttendee[];
    responseStatus?: GCalResponseStatus;
    eventType?: GCalEventType;
    template: StoredRoutineTemplate;
    active: boolean;
    createdTs: string;
    updatedTs: string;
    /**
     * ISO date (YYYY-MM-DD) — anchors the rrule schedule. Falls back to createdTs when unset.
     * User-editable in the routine edit dialog. For calendar routines, becomes the GCal series DTSTART
     * (snapped forward to the first BYDAY/BYMONTHDAY match). For nextAction routines, no items are
     * generated with an occurrence date before startDate.
     */
    startDate?: string;
    /** Present when routineType === 'calendar'. Defines time + duration (or all-day flag) for generated calendar items. */
    calendarItemTemplate?: {
        allDay?: boolean; // when true, timeOfDay/duration are ignored; generated items are all-day single-day
        timeOfDay?: string; // HH:MM (24h) — start time. Required when !allDay.
        duration?: number; // minutes. Required when !allDay.
    };
    /** ISO date of the most recently generated calendar item. Used to avoid scanning items for the next occurrence. */
    lastGeneratedDate?: string;
    /** Exception dates in the rrule series. 'skipped' when trashed; 'modified' when GCal moves the occurrence. */
    routineExceptions?: Array<{
        date: string; // ISO date of the original rrule occurrence
        type: 'skipped' | 'modified';
        itemId?: string;
        newTimeStart?: string; // ISO datetime — present when type === 'modified'
        newTimeEnd?: string;
        title?: string; // overridden title — present when GCal instance title differs from master
        notes?: string; // overridden description — present when GCal instance description differs from master
        /** Per-instance GCal-owned overrides. Absent ⇒ inherit master. See RoutineInterface. */
        organizer?: GCalPerson;
        creator?: GCalPerson;
        attendees?: GCalAttendee[];
        responseStatus?: GCalResponseStatus;
        eventType?: GCalEventType;
    }>;
}

export interface StoredPerson {
    _id: string;
    userId: string;
    name: string;
    email?: string;
    phone?: string;
    externalCalendarId?: string;
    notes?: string;
    createdTs: string;
    updatedTs: string;
}

export interface StoredWorkContext {
    _id: string;
    userId: string;
    name: string; // e.g. "near a phone", "at work", "with family"
    createdTs: string;
    updatedTs: string;
}

/** Per-calendar sync configuration — one OAuth integration can sync multiple Google Calendars. */
export interface StoredCalendarSyncConfig {
    _id: string;
    integrationId: string;
    user: string;
    calendarId: string;
    displayName?: string;
    isDefault: boolean;
    enabled: boolean;
    lastSyncedTs?: string;
    syncToken?: string;
    webhookChannelId?: string;
    webhookResourceId?: string;
    webhookExpiry?: string;
    createdTs: string;
    updatedTs: string;
}

export type StoredEntity = StoredItem | StoredRoutine | StoredPerson | StoredWorkContext;

/**
 * Device-local unsaved-input draft. Never synced to the server — drafts exist so text typed into a
 * capture/edit surface survives reloads and navigation until it is committed as a real entity write.
 * `kind` discriminates future draft shapes; keys embed the kind + owning scope (see draftHelpers).
 */
export interface StoredInboxCaptureDraft {
    key: string; // `inboxCapture:<userId>`
    kind: 'inboxCapture';
    userId: string;
    title: string;
    notes: string;
    updatedTs: string; // ISO datetime of the last local keystroke flush
}

export type StoredDraft = StoredInboxCaptureDraft;

/**
 * Singleton record holding device-scoped state — the stable deviceId and the cross-context flush
 * lock. Split from `StoredSyncCursor` because the device identity and flush coordination are
 * shared across every Better Auth session on this device, while pull cursors must be per-user.
 */
export interface StoredDeviceMeta {
    _id: 'local'; // singleton
    deviceId: string; // stable UUID generated on first launch; sent with every push/pull request
    flushingTs: string | null; // ISO datetime — cross-context flush lock between main thread and SW
}

/**
 * Per-user pull cursor. One row per Better Auth account currently logged in on this device — a
 * shared cursor lets one session's pull advance past another session's boundary op (the bug fix
 * that motivated the schema split). Keyed by Better Auth userId.
 */
export interface StoredSyncCursor {
    userId: string;
    lastSyncedTs: string; // ISO datetime of the last successful pull for this (device, user) pair
    // `_id` of the last pulled op, paired with `lastSyncedTs` so the cursor advances on the totally-
    // ordered `(ts, _id)` pair — a same-`ts` batch can't be split across two pulls and lose ops.
    // Backfilled to '' by the v6 migration on rows written before this field existed.
    lastSyncedId: string;
}

/** RSVP payload mirrored from RsvpOpPayload on the server side. */
export interface StoredRsvpOpPayload {
    itemId: string;
    calendarEventId: string;
    calendarIntegrationId: string;
    responseStatus: GCalResponseStatus;
}

export interface SyncOperation {
    id?: number; // auto-increment — omitted before insertion
    /**
     * Owning user id (Better Auth UUID). Required so the multi-account flush can fan out per user
     * — `flushSyncQueue({ userIdFilter })` keeps each per-account flush scoped to ops queued under
     * that account's active session, avoiding cross-account leakage when the active session is
     * pivoted between flushes by `syncAllLoggedInUsers`.
     */
    userId: string;
    entityType: EntityType;
    entityId: string;
    opType: OpType;
    queuedAt: string; // ISO datetime — determines replay order when multiple ops are queued offline
    /**
     * Full entity state at the time of the operation. null for delete operations.
     * Stored as a snapshot (not a diff) so last-write-wins resolution is trivial on the server.
     * Null for opType === 'rsvp' (use `rsvp` sidecar instead).
     */
    snapshot: StoredEntity | null;
    /** Captured at edit time from SendUpdatesDialog; replays through pushback on flush. */
    gcalMeta?: { sendUpdates: 'all' | 'none' };
    /** Required when opType === 'rsvp'; absent otherwise. */
    rsvp?: StoredRsvpOpPayload;
}

export interface MyDB extends DBSchema {
    // All known accounts across all sign-ins
    accounts: {
        key: string; // StoredAccount.id
        value: StoredAccount;
        indexes: { email: string };
    };
    // Single-entry store: which account is currently active (matches the live Better Auth session)
    activeAccount: {
        key: 'active';
        value: { userId: string };
    };
    // All GTD items for all accounts on this device
    items: {
        key: string; // StoredItem._id
        value: StoredItem;
        indexes: { userId: string };
    };
    // Recurring task definitions
    routines: {
        key: string; // StoredRoutine._id
        value: StoredRoutine;
        indexes: { userId: string };
    };
    // Named people referenced in items and waitingFor
    people: {
        key: string; // StoredPerson._id
        value: StoredPerson;
        indexes: { userId: string };
    };
    // Named work contexts used to tag and filter nextAction items
    workContexts: {
        key: string; // StoredWorkContext._id
        value: StoredWorkContext;
        indexes: { userId: string };
    };
    // Pending mutations to replay against the server when connectivity is restored
    syncOperations: {
        key: number; // auto-increment
        value: SyncOperation;
    };
    // Device-scoped state: stable deviceId + flush lock. Singleton keyed by 'local'.
    deviceMeta: {
        key: 'local';
        value: StoredDeviceMeta;
    };
    // Per-user pull cursors. One row per logged-in Better Auth account.
    syncCursors: {
        key: string; // StoredSyncCursor.userId
        value: StoredSyncCursor;
    };
    // Device-local unsaved-input drafts (inbox capture, …). Never synced; cleared on commit.
    drafts: {
        key: string; // StoredDraft.key
        value: StoredDraft;
    };
}
