/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWorkContextsRouteImport } from './routes/_authenticated/work-contexts'
import { Route as AuthenticatedWeeklyReviewRouteImport } from './routes/_authenticated/weekly-review'
import { Route as AuthenticatedWaitingForRouteImport } from './routes/_authenticated/waiting-for'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTicklerRouteImport } from './routes/_authenticated/tickler'
import { Route as AuthenticatedSomedayRouteImport } from './routes/_authenticated/someday'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRoutinesRouteImport } from './routes/_authenticated/routines'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedNextActionsRouteImport } from './routes/_authenticated/next-actions'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDoneRouteImport } from './routes/_authenticated/done'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedItemItemIdRouteImport } from './routes/_authenticated/item.$itemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkContextsRoute =
  AuthenticatedWorkContextsRouteImport.update({
    id: '/work-contexts',
    path: '/work-contexts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWeeklyReviewRoute =
  AuthenticatedWeeklyReviewRouteImport.update({
    id: '/weekly-review',
    path: '/weekly-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWaitingForRoute = AuthenticatedWaitingForRouteImport.update({
  id: '/waiting-for',
  path: '/waiting-for',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicklerRoute = AuthenticatedTicklerRouteImport.update({
  id: '/tickler',
  path: '/tickler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSomedayRoute = AuthenticatedSomedayRouteImport.update({
  id: '/someday',
  path: '/someday',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutinesRoute = AuthenticatedRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNextActionsRoute =
  AuthenticatedNextActionsRouteImport.update({
    id: '/next-actions',
    path: '/next-actions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoneRoute = AuthenticatedDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemItemIdRoute = AuthenticatedItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/done': typeof AuthenticatedDoneRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/next-actions': typeof AuthenticatedNextActionsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/someday': typeof AuthenticatedSomedayRoute
  '/tickler': typeof AuthenticatedTicklerRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/waiting-for': typeof AuthenticatedWaitingForRoute
  '/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/work-contexts': typeof AuthenticatedWorkContextsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/item/$itemId': typeof AuthenticatedItemItemIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/done': typeof AuthenticatedDoneRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/next-actions': typeof AuthenticatedNextActionsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/someday': typeof AuthenticatedSomedayRoute
  '/tickler': typeof AuthenticatedTicklerRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/waiting-for': typeof AuthenticatedWaitingForRoute
  '/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/work-contexts': typeof AuthenticatedWorkContextsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/item/$itemId': typeof AuthenticatedItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/done': typeof AuthenticatedDoneRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/next-actions': typeof AuthenticatedNextActionsRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/routines': typeof AuthenticatedRoutinesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/someday': typeof AuthenticatedSomedayRoute
  '/_authenticated/tickler': typeof AuthenticatedTicklerRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/waiting-for': typeof AuthenticatedWaitingForRoute
  '/_authenticated/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/_authenticated/work-contexts': typeof AuthenticatedWorkContextsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/item/$itemId': typeof AuthenticatedItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/done'
    | '/inbox'
    | '/next-actions'
    | '/people'
    | '/routines'
    | '/search'
    | '/settings'
    | '/someday'
    | '/tickler'
    | '/trash'
    | '/waiting-for'
    | '/weekly-review'
    | '/work-contexts'
    | '/auth/callback'
    | '/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/done'
    | '/inbox'
    | '/next-actions'
    | '/people'
    | '/routines'
    | '/search'
    | '/settings'
    | '/someday'
    | '/tickler'
    | '/trash'
    | '/waiting-for'
    | '/weekly-review'
    | '/work-contexts'
    | '/auth/callback'
    | '/'
    | '/item/$itemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/calendar'
    | '/_authenticated/done'
    | '/_authenticated/inbox'
    | '/_authenticated/next-actions'
    | '/_authenticated/people'
    | '/_authenticated/routines'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/someday'
    | '/_authenticated/tickler'
    | '/_authenticated/trash'
    | '/_authenticated/waiting-for'
    | '/_authenticated/weekly-review'
    | '/_authenticated/work-contexts'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work-contexts': {
      id: '/_authenticated/work-contexts'
      path: '/work-contexts'
      fullPath: '/work-contexts'
      preLoaderRoute: typeof AuthenticatedWorkContextsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weekly-review': {
      id: '/_authenticated/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof AuthenticatedWeeklyReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/waiting-for': {
      id: '/_authenticated/waiting-for'
      path: '/waiting-for'
      fullPath: '/waiting-for'
      preLoaderRoute: typeof AuthenticatedWaitingForRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickler': {
      id: '/_authenticated/tickler'
      path: '/tickler'
      fullPath: '/tickler'
      preLoaderRoute: typeof AuthenticatedTicklerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/someday': {
      id: '/_authenticated/someday'
      path: '/someday'
      fullPath: '/someday'
      preLoaderRoute: typeof AuthenticatedSomedayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routines': {
      id: '/_authenticated/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthenticatedRoutinesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/next-actions': {
      id: '/_authenticated/next-actions'
      path: '/next-actions'
      fullPath: '/next-actions'
      preLoaderRoute: typeof AuthenticatedNextActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/done': {
      id: '/_authenticated/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof AuthenticatedDoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/item/$itemId': {
      id: '/_authenticated/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof AuthenticatedItemItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDoneRoute: typeof AuthenticatedDoneRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedNextActionsRoute: typeof AuthenticatedNextActionsRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedRoutinesRoute: typeof AuthenticatedRoutinesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSomedayRoute: typeof AuthenticatedSomedayRoute
  AuthenticatedTicklerRoute: typeof AuthenticatedTicklerRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedWaitingForRoute: typeof AuthenticatedWaitingForRoute
  AuthenticatedWeeklyReviewRoute: typeof AuthenticatedWeeklyReviewRoute
  AuthenticatedWorkContextsRoute: typeof AuthenticatedWorkContextsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedItemItemIdRoute: typeof AuthenticatedItemItemIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDoneRoute: AuthenticatedDoneRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedNextActionsRoute: AuthenticatedNextActionsRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedRoutinesRoute: AuthenticatedRoutinesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSomedayRoute: AuthenticatedSomedayRoute,
  AuthenticatedTicklerRoute: AuthenticatedTicklerRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedWaitingForRoute: AuthenticatedWaitingForRoute,
  AuthenticatedWeeklyReviewRoute: AuthenticatedWeeklyReviewRoute,
  AuthenticatedWorkContextsRoute: AuthenticatedWorkContextsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedItemItemIdRoute: AuthenticatedItemItemIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
