/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCollectImport } from './routes/_authenticated/collect'
import { Route as AuthenticatedClarifyImport } from './routes/_authenticated/clarify'
import { Route as AuthenticatedListsInboxImport } from './routes/_authenticated/lists/inbox'
import { Route as AuthenticatedItemsIdImport } from './routes/_authenticated/items/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCollectRoute = AuthenticatedCollectImport.update({
  path: '/collect',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedClarifyRoute = AuthenticatedClarifyImport.update({
  path: '/clarify',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedListsInboxRoute = AuthenticatedListsInboxImport.update({
  path: '/lists/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedItemsIdRoute = AuthenticatedItemsIdImport.update({
  path: '/items/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/clarify': {
      id: '/_authenticated/clarify'
      path: '/clarify'
      fullPath: '/clarify'
      preLoaderRoute: typeof AuthenticatedClarifyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/collect': {
      id: '/_authenticated/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof AuthenticatedCollectImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/items/$id': {
      id: '/_authenticated/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AuthenticatedItemsIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/lists/inbox': {
      id: '/_authenticated/lists/inbox'
      path: '/lists/inbox'
      fullPath: '/lists/inbox'
      preLoaderRoute: typeof AuthenticatedListsInboxImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedClarifyRoute: typeof AuthenticatedClarifyRoute
  AuthenticatedCollectRoute: typeof AuthenticatedCollectRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedItemsIdRoute: typeof AuthenticatedItemsIdRoute
  AuthenticatedListsInboxRoute: typeof AuthenticatedListsInboxRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClarifyRoute: AuthenticatedClarifyRoute,
  AuthenticatedCollectRoute: AuthenticatedCollectRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedItemsIdRoute: AuthenticatedItemsIdRoute,
  AuthenticatedListsInboxRoute: AuthenticatedListsInboxRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/clarify': typeof AuthenticatedClarifyRoute
  '/collect': typeof AuthenticatedCollectRoute
  '/': typeof AuthenticatedIndexRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/lists/inbox': typeof AuthenticatedListsInboxRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clarify': typeof AuthenticatedClarifyRoute
  '/collect': typeof AuthenticatedCollectRoute
  '/': typeof AuthenticatedIndexRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/lists/inbox': typeof AuthenticatedListsInboxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/clarify': typeof AuthenticatedClarifyRoute
  '/_authenticated/collect': typeof AuthenticatedCollectRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/items/$id': typeof AuthenticatedItemsIdRoute
  '/_authenticated/lists/inbox': typeof AuthenticatedListsInboxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/clarify'
    | '/collect'
    | '/'
    | '/items/$id'
    | '/lists/inbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/clarify' | '/collect' | '/' | '/items/$id' | '/lists/inbox'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/clarify'
    | '/_authenticated/collect'
    | '/_authenticated/'
    | '/_authenticated/items/$id'
    | '/_authenticated/lists/inbox'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/clarify",
        "/_authenticated/collect",
        "/_authenticated/",
        "/_authenticated/items/$id",
        "/_authenticated/lists/inbox"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/clarify": {
      "filePath": "_authenticated/clarify.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/collect": {
      "filePath": "_authenticated/collect.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/items/$id": {
      "filePath": "_authenticated/items/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/lists/inbox": {
      "filePath": "_authenticated/lists/inbox.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
