/**
 * `applyServerItemBrief` — the on-demand generate endpoint hands a brief row straight back to the
 * device. It must land through the pull path's LWW rule (so the SSE op that follows is a no-op
 * and an older snapshot never clobbers a newer local row) and never queue a sync op of its own.
 */
import type { IDBPDatabase } from 'idb';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('#api/syncClient', async () => await import('../api/syncClient.mock.ts'));

import type { ServerItemBriefSnapshot } from '../api/briefApi';
import { applyServerItemBrief } from '../db/syncHelpers';
import type { MyDB, StoredItemBrief } from '../types/MyDB';
import { openTestDB } from './openTestDB';

const USER_ID = 'user-1';

function localBrief(overrides: Partial<StoredItemBrief> = {}): StoredItemBrief {
    return {
        _id: 'item-1',
        itemId: 'item-1',
        userId: USER_ID,
        text: 'Typed by the user',
        origin: 'user',
        sourceHash: 'h1',
        generatedTs: '2026-09-20T10:00:00.000Z',
        createdTs: '2026-09-20T10:00:00.000Z',
        updatedTs: '2026-09-20T10:00:00.000Z',
        ...overrides,
    };
}

function serverBrief(overrides: Partial<ServerItemBriefSnapshot> = {}): ServerItemBriefSnapshot {
    return {
        _id: 'item-1',
        itemId: 'item-1',
        user: USER_ID,
        text: '[fake] Generated by the model.',
        origin: 'model',
        model: 'fake',
        sourceHash: 'h1',
        generatedTs: '2026-09-20T10:05:00.000Z',
        createdTs: '2026-09-20T10:00:00.000Z',
        updatedTs: '2026-09-20T10:05:00.000Z',
        ...overrides,
    };
}

let db: IDBPDatabase<MyDB>;

beforeEach(async () => {
    db = await openTestDB();
});

afterEach(() => {
    db.close();
    vi.clearAllMocks();
});

describe('applyServerItemBrief', () => {
    it('stores a row for an item with no local brief, remapping user → userId, and queues no sync op', async () => {
        await applyServerItemBrief(db, serverBrief());
        const stored = await db.get('itemBriefs', 'item-1');
        expect(stored).toEqual(
            localBrief({
                text: '[fake] Generated by the model.',
                origin: 'model',
                model: 'fake',
                generatedTs: '2026-09-20T10:05:00.000Z',
                updatedTs: '2026-09-20T10:05:00.000Z',
            }),
        );
        expect(stored && 'user' in stored).toBe(false);
        expect(await db.getAll('syncOperations')).toEqual([]);
    });

    it('a newer server snapshot replaces the older local row', async () => {
        await db.put('itemBriefs', localBrief());
        await applyServerItemBrief(db, serverBrief({ updatedTs: '2026-09-20T10:05:00.000Z' }));
        expect((await db.get('itemBriefs', 'item-1'))?.text).toBe('[fake] Generated by the model.');
    });

    it('an older server snapshot does not overwrite a newer local row (LWW)', async () => {
        await db.put('itemBriefs', localBrief({ updatedTs: '2026-09-20T10:10:00.000Z' }));
        await applyServerItemBrief(db, serverBrief({ updatedTs: '2026-09-20T10:05:00.000Z' }));
        const stored = await db.get('itemBriefs', 'item-1');
        expect(stored?.text).toBe('Typed by the user');
        expect(stored?.origin).toBe('user');
        expect(await db.getAll('syncOperations')).toEqual([]);
    });

    it('is idempotent: re-applying the same snapshot (the SSE-delivered op) leaves one unchanged row', async () => {
        await applyServerItemBrief(db, serverBrief());
        await applyServerItemBrief(db, serverBrief());
        const rows = await db.getAll('itemBriefs');
        expect(rows).toHaveLength(1);
        const [row] = rows;
        if (!row) throw new Error('expected one brief row');
        expect(row.updatedTs).toBe('2026-09-20T10:05:00.000Z');
    });

    it('stores a skipped row with text: null verbatim', async () => {
        await applyServerItemBrief(db, serverBrief({ text: null, origin: 'skipped' }));
        const stored = await db.get('itemBriefs', 'item-1');
        expect(stored?.text).toBeNull();
        expect(stored?.origin).toBe('skipped');
        expect(await db.getAll('syncOperations')).toEqual([]);
    });
});
