import { expect, test } from '@playwright/test';
import dayjs from 'dayjs';
import { withOneLoggedInDevice } from './helpers/context';
import { gtd } from './helpers/gtd';

// The tickler midnight rollover (GTD item 8260d68a): a page left open across local midnight must
// reveal that day's tickler items on its own — no reload, no navigation, no sync nudge. The app's
// single self-rescheduling day-clock timer (client/src/lib/dayClock.ts) fires just past midnight
// and rolls every ignoreBefore filter to the new local day.

test.describe('Tickler midnight rollover', () => {
    test('a next action snoozed until tomorrow appears at local midnight with no reload', async ({ browser }) => {
        await withOneLoggedInDevice(browser, `tickler-midnight-${dayjs().valueOf()}@example.com`, async (page) => {
            // Everything derives from the fake start instant, so the snooze date and the faked
            // clock can never disagree — even if the real wall clock crosses midnight mid-test.
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const tomorrow = fakeStart.add(1, 'day').format('YYYY-MM-DD');

            const captured = await gtd.collect(page, 'Water the plants');
            await gtd.clarifyToNextAction(page, captured, { ignoreBefore: tomorrow });
            // Flush before goto — navigating mid-flush wedges the IDB sync-queue lock (~30s stall).
            await gtd.flush(page);

            // Boot the page under a fake clock parked two minutes before local midnight. install()
            // must precede the navigation so the app's day clock arms itself against fake time.
            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/next-actions');
            // The list legitimately renders empty pre-midnight — wait on the page shell, not a row.
            await expect(page.getByRole('heading', { name: 'Next Actions' })).toBeVisible();

            // 23:58 — the item is still snoozed (ignoreBefore = tomorrow > today).
            await expect(page.getByTestId('nextActionItemRow').filter({ hasText: 'Water the plants' })).toHaveCount(0);

            // Cross midnight: the day-clock timer (armed for 00:00:01) fires and re-renders the
            // filters against the new local day. No reload happens here — the page handle stays
            // live across the assertion, which is exactly the "left open across midnight" scenario.
            await page.clock.runFor(5 * 60 * 1000);

            await expect(page.getByTestId('nextActionItemRow').filter({ hasText: 'Water the plants' })).toBeVisible();
        });
    });

    test('the tickler page drops the row at midnight as it graduates to next actions', async ({ browser }) => {
        await withOneLoggedInDevice(browser, `tickler-midnight-page-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const tomorrow = fakeStart.add(1, 'day').format('YYYY-MM-DD');

            const captured = await gtd.collect(page, 'Renew passport');
            await gtd.clarifyToNextAction(page, captured, { ignoreBefore: tomorrow });
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/tickler');
            await expect(page.getByText('Renew passport')).toBeVisible();

            await page.clock.runFor(5 * 60 * 1000);

            // At fake-midnight the row leaves the tickler (it is now due today, not snoozed).
            await expect(page.getByText('Renew passport')).toHaveCount(0);
        });
    });

    test('completing a daily routine item near midnight snoozes its successor until tomorrow, then reveals it at midnight', async ({ browser }) => {
        // The core user story of the day-boundary fix, end-to-end: the successor is generated by
        // the client's completion-anchored floating-date math (createNextRoutineItem) and revealed
        // by the day clock — one flow chaining both halves, no reload in between.
        await withOneLoggedInDevice(browser, `tickler-routine-midnight-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const tomorrow = fakeStart.add(1, 'day').format('YYYY-MM-DD');

            // Created under the REAL clock (same calendar day as fakeStart) — today's item lands
            // with expectedBy = today and is therefore visible when the faked page opens.
            const routine = await gtd.createRoutine(page, {
                title: 'Take vitamins',
                routineType: 'nextAction',
                rrule: 'FREQ=DAILY',
                template: {},
                active: true,
            });
            await gtd.materializePendingNextActionRoutines(page);
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/next-actions');
            const row = page.getByTestId('nextActionItemRow').filter({ hasText: 'Take vitamins' });
            await expect(row).toBeVisible();

            // Complete today's occurrence in the UI at fake 23:58. The client anchors the
            // successor on the completion's LOCAL calendar date, so a near-midnight completion
            // still schedules "tomorrow", not "the day after".
            await row.locator('..').getByRole('button', { name: 'Mark done' }).click();
            await expect(row).toHaveCount(0);

            // The successor exists, is stamped for tomorrow, and is tickler-hidden until then.
            const items = await gtd.listItems(page);
            const successor = items.find((i) => i.routineId === routine._id && i.status === 'nextAction');
            if (!successor) throw new Error('expected a successor routine item after completion');
            expect(successor.expectedBy).toBe(tomorrow);
            expect(successor.ignoreBefore).toBe(tomorrow);

            // Cross midnight — the successor reveals itself with no reload and no sync nudge.
            await page.clock.runFor(5 * 60 * 1000);
            await expect(page.getByTestId('nextActionItemRow').filter({ hasText: 'Take vitamins' })).toBeVisible();
        });
    });

    test('a suspended-laptop wake-up after midnight reveals the item via the focus recheck', async ({ browser }) => {
        // Genuine suspend simulation: setSystemTime jumps the wall clock WITHOUT firing timers —
        // the armed midnight timeout never runs, exactly like a lid closed across midnight. The
        // focus wake-up listener must catch the missed boundary.
        await withOneLoggedInDevice(browser, `tickler-wakeup-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const tomorrow = fakeStart.add(1, 'day').format('YYYY-MM-DD');

            const captured = await gtd.collect(page, 'Defrost freezer');
            await gtd.clarifyToNextAction(page, captured, { ignoreBefore: tomorrow });
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/next-actions');
            await expect(page.getByRole('heading', { name: 'Next Actions' })).toBeVisible();
            await expect(page.getByTestId('nextActionItemRow').filter({ hasText: 'Defrost freezer' })).toHaveCount(0);

            await page.clock.setSystemTime(fakeStart.add(1, 'day').hour(9).minute(0).toDate());
            await page.evaluate(() => window.dispatchEvent(new Event('focus')));

            await expect(page.getByTestId('nextActionItemRow').filter({ hasText: 'Defrost freezer' })).toBeVisible();
        });
    });

    test('items snoozed +1/+2/+3 days each appear only on their own day across three midnights', async ({ browser }) => {
        // Soak: the timer must re-arm itself day after day (the self-rescheduling property), and
        // early reveals matter as much as reveals — each later item must stay hidden on the
        // earlier days. fastForward (not runFor) for the 24h jumps: it fires due timers at most
        // once, so app polling intervals don't replay a full day of ticks per jump.
        await withOneLoggedInDevice(browser, `tickler-soak-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const titlesByOffset: Array<[number, string]> = [
                [1, 'Soak day one'],
                [2, 'Soak day two'],
                [3, 'Soak day three'],
            ];
            for (const [offset, title] of titlesByOffset) {
                const captured = await gtd.collect(page, title);
                await gtd.clarifyToNextAction(page, captured, { ignoreBefore: fakeStart.add(offset, 'day').format('YYYY-MM-DD') });
            }
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/next-actions');
            await expect(page.getByRole('heading', { name: 'Next Actions' })).toBeVisible();
            const rowFor = (title: string) => page.getByTestId('nextActionItemRow').filter({ hasText: title });
            for (const [, title] of titlesByOffset) {
                await expect(rowFor(title)).toHaveCount(0);
            }

            await page.clock.runFor(5 * 60 * 1000); // first midnight
            await expect(rowFor('Soak day one')).toBeVisible();
            await expect(rowFor('Soak day two')).toHaveCount(0);
            await expect(rowFor('Soak day three')).toHaveCount(0);

            await page.clock.fastForward(24 * 60 * 60 * 1000); // second midnight
            await expect(rowFor('Soak day two')).toBeVisible();
            await expect(rowFor('Soak day three')).toHaveCount(0);

            await page.clock.fastForward(24 * 60 * 60 * 1000); // third midnight
            await expect(rowFor('Soak day three')).toBeVisible();
        });
    });

    test('the waiting-for overdue marker turns on at local midnight without a reload', async ({ browser }) => {
        // isOverdue is expectedBy < todayIso — an item expected "today" flips to overdue the
        // moment the local day rolls. This is the /waiting-for consumer of the shared day clock.
        await withOneLoggedInDevice(browser, `tickler-overdue-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const today = fakeStart.format('YYYY-MM-DD');

            const captured = await gtd.collect(page, 'Contract countersignature');
            await gtd.clarifyToWaitingFor(page, captured, { expectedBy: today });
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/waiting-for');
            const row = page.getByTestId('waitingForItemRow').filter({ hasText: 'Contract countersignature' });
            await expect(row).toBeVisible();
            await expect(row.filter({ hasText: 'overdue' })).toHaveCount(0);

            await page.clock.runFor(5 * 60 * 1000);

            await expect(row.filter({ hasText: 'overdue' })).toBeVisible();
        });
    });

    test('a snoozed waitingFor item lives on /tickler alone, then joins /waiting-for at midnight', async ({ browser }) => {
        // The extend-the-filter decision: /waiting-for now applies the same isTicklerHidden
        // predicate as /next-actions, so a snoozed delegation no longer double-lists — it sits on
        // the tickler until its date and graduates at local midnight with no reload.
        await withOneLoggedInDevice(browser, `tickler-waiting-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const tomorrow = fakeStart.add(1, 'day').format('YYYY-MM-DD');

            const captured = await gtd.collect(page, 'Loaner cello returned');
            await gtd.clarifyToWaitingFor(page, captured, { ignoreBefore: tomorrow });
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            // Reachability half: while snoozed, the ONE place the item shows is the tickler.
            await page.goto('/tickler');
            await expect(page.getByTestId('ticklerItemRow').filter({ hasText: 'Loaner cello returned' })).toBeVisible();

            await page.goto('/waiting-for');
            await expect(page.getByRole('heading', { name: 'Waiting For' })).toBeVisible();
            await expect(page.getByTestId('waitingForItemRow').filter({ hasText: 'Loaner cello returned' })).toHaveCount(0);

            await page.clock.runFor(5 * 60 * 1000);

            await expect(page.getByTestId('waitingForItemRow').filter({ hasText: 'Loaner cello returned' })).toBeVisible();
        });
    });

    test('a snoozed somedayMaybe item lives on /tickler alone, then joins /someday at midnight', async ({ browser }) => {
        // Same decision for /someday — and the tickler page must list somedayMaybe (it previously
        // did not), otherwise a snoozed parked item would be reachable nowhere at all.
        await withOneLoggedInDevice(browser, `tickler-someday-${dayjs().valueOf()}@example.com`, async (page) => {
            const fakeStart = dayjs().hour(23).minute(58).second(0);
            const tomorrow = fakeStart.add(1, 'day').format('YYYY-MM-DD');

            const captured = await gtd.collect(page, 'Learn glassblowing');
            await gtd.clarifyToSomedayMaybe(page, captured, { ignoreBefore: tomorrow });
            await gtd.flush(page);

            await page.clock.install({ time: fakeStart.toDate() });
            await page.goto('/tickler');
            await expect(page.getByTestId('ticklerItemRow').filter({ hasText: 'Learn glassblowing' })).toBeVisible();

            await page.goto('/someday');
            await expect(page.getByRole('heading', { name: 'Someday / Maybe' })).toBeVisible();
            await expect(page.getByTestId('somedayItemRow').filter({ hasText: 'Learn glassblowing' })).toHaveCount(0);

            await page.clock.runFor(5 * 60 * 1000);

            await expect(page.getByTestId('somedayItemRow').filter({ hasText: 'Learn glassblowing' })).toBeVisible();
        });
    });
});
