/** Regression coverage for the bug where deleting a `nextAction`-type routine left its generated
 * open item orphaned forever (routineId pointing at a deleted routine). The pre-existing cascade
 * (`trashGeneratedCalendarItems`) only ever trashed `status: 'calendar'` items; this suite covers
 * the sibling `trashGeneratedOpenNextActionItems` cascade added alongside it. */
/** biome-ignore-all lint/style/noNonNullAssertion: test code asserts result before using ! */
import dayjs from 'dayjs';
import { Hono } from 'hono';
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { issueApiToken } from '../auth/apiTokens.js';
import { __resetDefaultStoreForTests } from '../auth/rateLimitMiddleware.js';
import itemsDAO from '../dataAccess/itemsDAO.js';
import operationsDAO from '../dataAccess/operationsDAO.js';
import routinesDAO from '../dataAccess/routinesDAO.js';
import { auth, closeDataAccess, db, loadDataAccess } from '../loaders/mainLoader.js';
import { v1RoutinesRoutes } from '../routes/v1/routines.js';
import type { ApiTokenScope, ItemInterface, RoutineInterface } from '../types/entities.js';
import { oauthLogin, SESSION_COOKIE } from './helpers.js';

const app = new Hono().on(['GET', 'POST'], '/auth/*', (c) => auth.handler(c.req.raw)).route('/v1', v1RoutinesRoutes);

beforeAll(async () => {
    await loadDataAccess('gtd_test');
});

afterAll(async () => {
    await closeDataAccess();
});

beforeEach(async () => {
    await Promise.all([
        db.collection('user').deleteMany({}),
        db.collection('session').deleteMany({}),
        db.collection('account').deleteMany({}),
        db.collection('verification').deleteMany({}),
        db.collection('apiTokens').deleteMany({}),
        db.collection('routines').deleteMany({}),
        db.collection('items').deleteMany({}),
        db.collection('operations').deleteMany({}),
    ]);
    __resetDefaultStoreForTests();
    vi.restoreAllMocks();
});

async function login(): Promise<string> {
    const { sessionCookie } = await oauthLogin(app, 'google');
    const sessionRes = await app.fetch(new Request('http://localhost:4000/auth/get-session', { headers: { Cookie: `${SESSION_COOKIE}=${sessionCookie}` } }));
    const { user } = (await sessionRes.json()) as { user: { id: string } };
    return user.id;
}

async function tokenWith(userId: string, scopes: ApiTokenScope[]): Promise<string> {
    const { plaintext } = await issueApiToken(userId, 't', scopes);
    return plaintext;
}

function makeRoutine(userId: string, overrides: Partial<RoutineInterface> = {}): RoutineInterface {
    const now = dayjs().toISOString();
    return {
        _id: 'r-delete-cascade',
        user: userId,
        title: 'Withdraw cash',
        routineType: 'nextAction',
        rrule: 'FREQ=MONTHLY',
        template: {},
        active: true,
        createdTs: now,
        updatedTs: now,
        ...overrides,
    };
}

function makeItem(userId: string, routineId: string, overrides: Partial<ItemInterface> = {}): ItemInterface {
    const now = dayjs().toISOString();
    return {
        _id: `i-${Math.random()}`,
        user: userId,
        status: 'nextAction',
        title: 'Withdraw cash',
        routineId,
        expectedBy: now.slice(0, 10),
        createdTs: now,
        updatedTs: now,
        ...overrides,
    };
}

async function deleteRoutine(routineId: string, token: string): Promise<Response> {
    return app.fetch(new Request(`http://localhost:4000/v1/routines/${routineId}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }));
}

async function waitFor(predicate: () => Promise<boolean>, timeoutMs = 1000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        if (await predicate()) return;
        await new Promise((r) => setTimeout(r, 10));
    }
    throw new Error('waitFor: predicate never became true');
}

describe('DELETE /v1/routines/:id cascades to generated nextAction items', () => {
    it('trashes the open nextAction item generated by the deleted routine', async () => {
        const userId = await login();
        const token = await tokenWith(userId, ['routines.write']);
        await routinesDAO.insertOne(makeRoutine(userId));
        const item = makeItem(userId, 'r-delete-cascade');
        await itemsDAO.insertOne(item);

        const res = await deleteRoutine('r-delete-cascade', token);
        expect(res.status).toBe(200);

        await waitFor(async () => (await itemsDAO.findByOwnerAndId(item._id!, userId))?.status === 'trash');
        const stored = await itemsDAO.findByOwnerAndId(item._id!, userId);
        expect(stored?.status).toBe('trash');
        const ops = await operationsDAO.findArray({ entityId: item._id, opType: 'update' });
        expect(ops.length).toBeGreaterThanOrEqual(1);
    });

    it('trashes a past-due open item too — unlike pause, delete has no forward-looking date filter', async () => {
        const userId = await login();
        const token = await tokenWith(userId, ['routines.write']);
        await routinesDAO.insertOne(makeRoutine(userId));
        const pastDueItem = makeItem(userId, 'r-delete-cascade', { expectedBy: '2020-01-01' });
        await itemsDAO.insertOne(pastDueItem);

        const res = await deleteRoutine('r-delete-cascade', token);
        expect(res.status).toBe(200);

        await waitFor(async () => (await itemsDAO.findByOwnerAndId(pastDueItem._id!, userId))?.status === 'trash');
        const stored = await itemsDAO.findByOwnerAndId(pastDueItem._id!, userId);
        expect(stored?.status).toBe('trash');
    });

    it('does not touch already-done or already-trashed items', async () => {
        const userId = await login();
        const token = await tokenWith(userId, ['routines.write']);
        await routinesDAO.insertOne(makeRoutine(userId));
        const doneItem = makeItem(userId, 'r-delete-cascade', { status: 'done' });
        const trashedItem = makeItem(userId, 'r-delete-cascade', { status: 'trash' });
        await itemsDAO.insertOne(doneItem);
        await itemsDAO.insertOne(trashedItem);

        const res = await deleteRoutine('r-delete-cascade', token);
        expect(res.status).toBe(200);

        // Give the fire-and-forget cascade a moment to run (nothing to poll for since no state
        // should change) before asserting neither item was touched.
        await new Promise((r) => setTimeout(r, 100));
        const storedDone = await itemsDAO.findByOwnerAndId(doneItem._id!, userId);
        const storedTrashed = await itemsDAO.findByOwnerAndId(trashedItem._id!, userId);
        expect(storedDone?.updatedTs).toBe(doneItem.updatedTs);
        expect(storedTrashed?.updatedTs).toBe(trashedItem.updatedTs);
        expect(await operationsDAO.findArray({ entityId: doneItem._id, opType: 'update' })).toHaveLength(0);
        expect(await operationsDAO.findArray({ entityId: trashedItem._id, opType: 'update' })).toHaveLength(0);
    });

    it('no-ops cleanly when the routine has no generated items', async () => {
        const userId = await login();
        const token = await tokenWith(userId, ['routines.write']);
        await routinesDAO.insertOne(makeRoutine(userId));

        const res = await deleteRoutine('r-delete-cascade', token);
        expect(res.status).toBe(200);
    });

    it('leaves calendar-status items to the existing calendar cascade (regression guard)', async () => {
        const userId = await login();
        const token = await tokenWith(userId, ['routines.write']);
        await routinesDAO.insertOne(makeRoutine(userId, { routineType: 'calendar' }));
        const calendarItem = makeItem(userId, 'r-delete-cascade', {
            status: 'calendar',
            timeStart: '2026-08-01T10:00:00Z',
            timeEnd: '2026-08-01T11:00:00Z',
        });
        await itemsDAO.insertOne(calendarItem);

        const res = await deleteRoutine('r-delete-cascade', token);
        expect(res.status).toBe(200);

        await waitFor(async () => (await itemsDAO.findByOwnerAndId(calendarItem._id!, userId))?.status === 'trash');
        const stored = await itemsDAO.findByOwnerAndId(calendarItem._id!, userId);
        expect(stored?.status).toBe('trash');
    });
});
