/**
 * Coverage for the sync doctor (`lib/syncDoctor.ts` + `POST /maintenance/sync-doctor`).
 *
 * Each check corresponds to a shipped bug class; the tests seed the exact corrupt shape that class
 * leaves behind and assert (a) the doctor reports it, (b) a clean dataset reports healthy, and
 * (c) the ONLY write path — the opt-in poisoned-watermark restamp — writes precisely what it
 * reports and records ops so other devices converge.
 */
import dayjs from 'dayjs';
import { Hono } from 'hono';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import itemsDAO from '../dataAccess/itemsDAO.js';
import operationsDAO from '../dataAccess/operationsDAO.js';
import routinesDAO from '../dataAccess/routinesDAO.js';
import { healPoisonedWatermark, runSyncDoctor } from '../lib/syncDoctor.js';
import { auth, closeDataAccess, db, loadDataAccess } from '../loaders/mainLoader.js';
import { maintenanceRoutes } from '../routes/maintenance.js';
import type { ItemInterface, RoutineInterface } from '../types/entities.js';
import { authenticatedRequest, oauthLogin, SESSION_COOKIE } from './helpers.js';

const app = new Hono().on(['GET', 'POST'], '/auth/*', (c) => auth.handler(c.req.raw)).route('/maintenance', maintenanceRoutes);

const USER = 'user-sync-doctor';
const NOW = '2026-07-27T12:00:00.000Z';

beforeAll(async () => {
    await loadDataAccess('gtd_test_sync_doctor');
});

afterAll(async () => {
    await closeDataAccess();
});

beforeEach(async () => {
    await Promise.all([
        db.collection('items').deleteMany({}),
        db.collection('routines').deleteMany({}),
        db.collection('people').deleteMany({}),
        db.collection('workContexts').deleteMany({}),
        db.collection('operations').deleteMany({}),
        db.collection('deviceSyncState').deleteMany({}),
        db.collection('calendarIntegrations').deleteMany({}),
        db.collection('user').deleteMany({}),
        db.collection('session').deleteMany({}),
        db.collection('account').deleteMany({}),
    ]);
});

function makeRoutine(id: string, overrides: Partial<RoutineInterface> = {}): RoutineInterface {
    return {
        _id: id,
        user: USER,
        title: 'Routine',
        routineType: 'calendar',
        rrule: 'FREQ=WEEKLY;BYDAY=MO',
        template: {},
        active: true,
        calendarItemTemplate: { timeOfDay: '09:00', duration: 30 },
        createdTs: '2026-01-01T00:00:00.000Z',
        updatedTs: '2026-01-01T00:00:00.000Z',
        ...overrides,
    };
}

function makeItem(id: string, overrides: Partial<ItemInterface> = {}): ItemInterface {
    return {
        _id: id,
        user: USER,
        title: 'Item',
        status: 'calendar',
        timeStart: '2026-08-01T09:00:00+03:00',
        timeEnd: '2026-08-01T09:30:00+03:00',
        createdTs: '2026-01-01T00:00:00.000Z',
        updatedTs: '2026-01-01T00:00:00.000Z',
        ...overrides,
    };
}

describe('runSyncDoctor — detection', () => {
    it('reports healthy on a clean dataset', async () => {
        await routinesDAO.insertOne(makeRoutine('r-clean', { calendarEventId: 'evt-clean', calendarIntegrationId: 'int-1' }));
        await db.collection('calendarIntegrations').insertOne({ _id: 'int-1', user: USER } as never);
        await itemsDAO.insertOne(makeItem('i-clean', { routineId: 'r-clean', calendarEventId: 'evt-clean-occurrence', calendarIntegrationId: 'int-1' }));

        const report = await runSyncDoctor(USER, NOW);

        expect(report.healthy).toBe(true);
        expect(report.healedPoisonedWatermarks).toBe(0);
    });

    it('reports two active routines sharing one GCal series', async () => {
        // The unique index normally forbids this — seed directly to simulate index-bypassing
        // writes (dropping the index for just these rows keeps the fixture honest).
        await db
            .collection('routines')
            .dropIndex('uniq_active_routine_per_gcal_series')
            .catch(() => undefined);
        await db
            .collection('routines')
            .insertMany([
                makeRoutine('r-dup-a', { calendarEventId: 'evt-dup', calendarIntegrationId: 'int-1' }),
                makeRoutine('r-dup-b', { calendarEventId: 'evt-dup', calendarIntegrationId: 'int-1' }),
            ] as never[]);

        const report = await runSyncDoctor(USER, NOW);

        expect(report.healthy).toBe(false);
        expect(report.duplicateActiveRoutineSeries).toHaveLength(1);
        const [finding] = report.duplicateActiveRoutineSeries;
        if (!finding) throw new Error('expected one duplicate-series finding');
        expect(finding.routineIds.sort()).toEqual(['r-dup-a', 'r-dup-b']);
    });

    it('reports live future items generated by an inactive routine, ignoring past ones', async () => {
        await routinesDAO.insertOne(makeRoutine('r-inactive', { active: false, calendarEventId: 'evt-phantom' }));
        await itemsDAO.insertMany([
            makeItem('i-phantom', { routineId: 'r-inactive', timeStart: '2026-08-01T09:00:00+03:00', calendarEventId: 'e1' }),
            makeItem('i-past', { routineId: 'r-inactive', timeStart: '2026-06-01T09:00:00+03:00', calendarEventId: 'e2' }),
        ]);

        const report = await runSyncDoctor(USER, NOW);

        expect(report.phantomItemsOnInactiveRoutines).toEqual([{ routineId: 'r-inactive', itemIds: ['i-phantom'] }]);
    });

    it('compares timeStart across timezone offsets, not lexicographically', async () => {
        await routinesDAO.insertOne(makeRoutine('r-tz', { active: false, calendarEventId: 'evt-tz' }));
        // 13:00+03:00 == 10:00Z, two hours BEFORE `now` (12:00Z) — a lexicographic compare against
        // the UTC `now` string would misread the "13:00" as future and report a phantom.
        await itemsDAO.insertOne(makeItem('i-past-offset', { routineId: 'r-tz', timeStart: '2026-07-27T13:00:00+03:00', calendarEventId: 'e-tz' }));

        const report = await runSyncDoctor(USER, NOW);

        expect(report.phantomItemsOnInactiveRoutines).toEqual([]);
    });

    it('reports duplicate live calendar items on one event', async () => {
        await db
            .collection('items')
            .dropIndex('uniq_calendar_item_per_event')
            .catch(() => undefined);
        await db
            .collection('items')
            .insertMany([makeItem('i-dup-a', { calendarEventId: 'evt-item-dup' }), makeItem('i-dup-b', { calendarEventId: 'evt-item-dup' })] as never[]);

        const report = await runSyncDoctor(USER, NOW);

        expect(report.duplicateLiveCalendarItems).toHaveLength(1);
        expect(report.duplicateLiveCalendarItems[0]?.itemIds.sort()).toEqual(['i-dup-a', 'i-dup-b']);
    });

    it('reports a cancellation-retirement-shaped routine missing the retiredByGCal marker, and skips a marked one', async () => {
        await routinesDAO.insertMany([
            makeRoutine('r-unmarked', { active: false, calendarEventId: 'evt-a', rrule: 'FREQ=WEEKLY;BYDAY=MO;UNTIL=20260101T235959Z' }),
            makeRoutine('r-marked', {
                active: false,
                calendarEventId: 'evt-b',
                rrule: 'FREQ=WEEKLY;BYDAY=MO;UNTIL=20260101T235959Z',
                retiredByGCal: true,
            }),
        ]);

        const report = await runSyncDoctor(USER, NOW);

        expect(report.unmarkedRetiredRoutines).toHaveLength(1);
        expect(report.unmarkedRetiredRoutines[0]?.routineId).toBe('r-unmarked');
    });

    it('reports future-stamped rows across entity types, and future device cursors', async () => {
        const poisonedTs = dayjs(NOW).add(2, 'hour').toISOString();
        await itemsDAO.insertOne(makeItem('i-poisoned', { status: 'inbox', updatedTs: poisonedTs }));
        await db.collection('people').insertOne({ _id: 'p-poisoned', user: USER, name: 'P', createdTs: NOW, updatedTs: poisonedTs } as never);
        await db.collection('deviceSyncState').insertMany([
            { _id: `dev-future::${USER}`, deviceId: 'dev-future', user: USER, lastSyncedTs: poisonedTs, lastSeenTs: NOW },
            { _id: `dev-ok::${USER}`, deviceId: 'dev-ok', user: USER, lastSyncedTs: NOW, lastSeenTs: NOW },
        ] as never[]);

        const report = await runSyncDoctor(USER, NOW);

        expect(report.poisonedWatermarks.map((f) => f.entityId).sort()).toEqual(['i-poisoned', 'p-poisoned']);
        expect(report.futureCursors).toEqual([{ deviceId: 'dev-future', lastSyncedTs: poisonedTs }]);
    });

    it('tolerates ordinary clock skew — rows a minute ahead are not poisoned', async () => {
        await itemsDAO.insertOne(makeItem('i-skewed', { status: 'inbox', updatedTs: dayjs(NOW).add(1, 'minute').toISOString() }));

        const report = await runSyncDoctor(USER, NOW);

        expect(report.poisonedWatermarks).toEqual([]);
        expect(report.healthy).toBe(true);
    });

    it('reports live entities pointing at a deleted calendar integration, ignoring trashed items', async () => {
        await itemsDAO.insertMany([
            makeItem('i-dangling', { calendarEventId: 'evt-d1', calendarIntegrationId: 'int-gone' }),
            makeItem('i-trashed', { status: 'trash', calendarEventId: 'evt-d2', calendarIntegrationId: 'int-gone' }),
        ]);
        await routinesDAO.insertOne(makeRoutine('r-dangling', { calendarEventId: 'evt-d3', calendarIntegrationId: 'int-gone' }));

        const report = await runSyncDoctor(USER, NOW);

        expect(report.danglingIntegrationRefs.map((f) => f.entityId).sort()).toEqual(['i-dangling', 'r-dangling']);
    });

    it('scopes every check to the requested user', async () => {
        await itemsDAO.insertOne(makeItem('i-other-user', { user: 'someone-else', status: 'inbox', updatedTs: dayjs(NOW).add(2, 'hour').toISOString() }));

        const report = await runSyncDoctor(USER, NOW);

        expect(report.healthy).toBe(true);
    });
});

describe('runSyncDoctor — poisoned-watermark healing (opt-in write)', () => {
    it('read-only by default: reports the poison but writes nothing', async () => {
        const poisonedTs = dayjs(NOW).add(2, 'hour').toISOString();
        await itemsDAO.insertOne(makeItem('i-poisoned', { status: 'inbox', updatedTs: poisonedTs }));

        const report = await runSyncDoctor(USER, NOW);

        expect(report.poisonedWatermarks).toHaveLength(1);
        expect(report.healedPoisonedWatermarks).toBe(0);
        expect((await itemsDAO.findByOwnerAndId('i-poisoned', USER))?.updatedTs).toBe(poisonedTs);
        expect(await operationsDAO.countDocuments({})).toBe(0);
    });

    it('restamps poisoned rows to now and records ops when healPoisonedWatermarks is set', async () => {
        const poisonedTs = dayjs(NOW).add(2, 'hour').toISOString();
        await itemsDAO.insertOne(makeItem('i-poisoned', { status: 'inbox', title: 'keep me', updatedTs: poisonedTs }));

        const report = await runSyncDoctor(USER, NOW, { healPoisonedWatermarks: true });

        expect(report.healedPoisonedWatermarks).toBe(1);
        const healed = await itemsDAO.findByOwnerAndId('i-poisoned', USER);
        expect(healed?.updatedTs).toBe(NOW);
        expect(healed?.title).toBe('keep me');
        const ops = await operationsDAO.findArray({ entityType: 'item', entityId: 'i-poisoned' });
        expect(ops).toHaveLength(1);
        const [op] = ops;
        if (!op) throw new Error('expected one restamp op');
        // The op must carry the POST-restamp snapshot — replaying the poisoned value would re-poison.
        expect((op.snapshot as ItemInterface).updatedTs).toBe(NOW);
    });

    it('skips a row whose state changed after the finding was taken (guarded re-read)', async () => {
        // Exercised directly: within one runSyncDoctor call the findings are always fresh, so the
        // guard only fires when a concurrent write lands between the state load and the restamp.
        const staleFindingTs = dayjs(NOW).add(2, 'hour').toISOString();
        const currentTs = dayjs(NOW).add(3, 'hour').toISOString();
        await itemsDAO.insertOne(makeItem('i-racing', { status: 'inbox', updatedTs: currentTs }));

        const op = await healPoisonedWatermark(USER, { entityType: 'item', entityId: 'i-racing', updatedTs: staleFindingTs }, NOW);

        expect(op).toBeNull();
        expect((await itemsDAO.findByOwnerAndId('i-racing', USER))?.updatedTs).toBe(currentTs);
        expect(await operationsDAO.countDocuments({})).toBe(0);
    });
});

describe('POST /maintenance/sync-doctor', () => {
    it('returns the caller-scoped report and defaults to read-only', async () => {
        const { sessionCookie } = await oauthLogin(app, 'google');
        if (!sessionCookie) throw new Error('expected a session cookie from oauth login');
        const res = await app.fetch(new Request('http://localhost:4000/auth/get-session', { headers: { Cookie: `${SESSION_COOKIE}=${sessionCookie}` } }));
        const { user } = (await res.json()) as { user: { id: string } };
        await db.collection('items').insertOne(makeItem('i-endpoint', { user: user.id, status: 'inbox', updatedTs: '2099-01-01T00:00:00.000Z' }) as never);

        const doctorRes = await authenticatedRequest(app, { method: 'POST', path: '/maintenance/sync-doctor', sessionCookie, body: {} });
        expect(doctorRes.status).toBe(200);
        const report = (await doctorRes.json()) as { healthy: boolean; poisonedWatermarks: unknown[]; healedPoisonedWatermarks: number };
        expect(report.healthy).toBe(false);
        expect(report.poisonedWatermarks).toHaveLength(1);
        expect(report.healedPoisonedWatermarks).toBe(0);
        expect((await db.collection('items').findOne({ _id: 'i-endpoint' }))?.updatedTs).toBe('2099-01-01T00:00:00.000Z');
    });

    it('rejects unauthenticated requests with 401', async () => {
        const res = await app.fetch(
            new Request('http://localhost:4000/maintenance/sync-doctor', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({}),
            }),
        );
        expect(res.status).toBe(401);
    });
});
