export const ItemStatus = {
    inbox: 'inbox',
    nextAction: 'nextAction',
    calendar: 'calendar',
    waitingFor: 'waitingFor',
    done: 'done',
    trash: 'trash',
} as const;
export type ItemStatus = (typeof ItemStatus)[keyof typeof ItemStatus];

export type EnergyLevel = 'low' | 'medium' | 'high';
export type EntityType = 'item' | 'routine' | 'person' | 'workContext';
export type OpType = 'create' | 'update' | 'delete';

export interface ItemInterface {
    /**
     * Client-generated UUID used as the MongoDB _id. Optional so MongoDB accepts documents created without one (e.g. in tests) but always present in practice.
     */
    _id?: string;
    user: string; // Better Auth user ID (UUID string, not ObjectId)
    status: ItemStatus;
    title: string;
    createdTs: string; // ISO datetime
    updatedTs: string; // ISO datetime — used as the conflict-resolution anchor (last write wins)
    /**
     * Refs to WorkContextInterface._id. Relevant for `nextAction` items.
     */
    workContextIds?: string[];
    /**
     * Refs to PersonInterface._id. Relevant for `nextAction` and `waitingFor` items.
     */
    peopleIds?: string[];
    /**
     * Ref to PersonInterface._id. The specific person being waited on (`waitingFor` items only).
     */
    waitingForPersonId?: string;
    /**
     * Deadline date (one-day resolution, ISO date string). Relevant for `nextAction` and `waitingFor` items.
     */
    expectedBy?: string;
    /**
     * Tickler date (ISO date string). Item is hidden from all lists until this date passes.
     * Applies to `nextAction` and `waitingFor` items. Separate from `timeStart` to avoid overloading.
     */
    ignoreBefore?: string;
    /**
     * Calendar event start datetime (ISO datetime string). `calendar` items only.
     */
    timeStart?: string;
    /**
     * Calendar event end datetime (ISO datetime string). `calendar` items only.
     */
    timeEnd?: string;
    /**
     * External calendar event ID (e.g. Google Calendar event ID). Set when this item is synced to a calendar.
     */
    calendarEventId?: string;
    /**
     * Ref to CalendarIntegrationInterface._id. Identifies which calendar integration owns the synced event.
     */
    calendarIntegrationId?: string;
    /**
     * Ref to RoutineInterface._id. Set when this item was generated by a routine.
     */
    routineId?: string;
    energy?: EnergyLevel; // relevant for `nextAction` items
    time?: number; // estimated duration in minutes — relevant for `nextAction` items
    focus?: boolean; // requires uninterrupted focus — relevant for `nextAction` items
    urgent?: boolean; // must be done very soon — relevant for `nextAction` items
    notes?: string; // freeform markdown notes — applies to all statuses
}

export interface RoutineItemTemplate {
    workContextIds?: string[];
    peopleIds?: string[];
    energy?: EnergyLevel;
    time?: number; // estimated minutes
    focus?: boolean;
    urgent?: boolean;
    /**
     * Days before expectedBy to set ignoreBefore (tickler). undefined = no tickler; 0 = show on due date.
     */
    ticklerLeadDays?: number;
    notes?: string;
}

export interface RoutineInterface {
    _id: string;
    user: string;
    title: string;
    /**
     * nextAction: next instance created after previous is done/trashed (all frequencies are after-completion).
     * calendar: next instance created on a fixed rrule schedule.
     */
    routineType: 'nextAction' | 'calendar';
    /**
     * RFC 5545 RRULE string (e.g. FREQ=WEEKLY;BYDAY=MO). Required for all routines.
     * For nextAction routines, DTSTART is set dynamically to the completion date when computing the next occurrence.
     * For calendar routines, DTSTART is the routine's creation date (fixed absolute schedule).
     */
    rrule: string;
    /**
     * @deprecated Use routineType instead.
     */
    triggerMode?: 'afterCompletion' | 'fixedSchedule';
    /**
     * @deprecated Use rrule instead.
     */
    afterCompletionDelayDays?: number;
    /**
     * Google Calendar recurring event series ID. Set when the routine is linked to a calendar series.
     */
    calendarEventId?: string;
    /**
     * Ref to CalendarIntegrationInterface._id. Identifies which calendar integration owns the series.
     */
    calendarIntegrationId?: string;
    /**
     * Fields copied onto each item instance generated by this routine.
     */
    template: RoutineItemTemplate;
    active: boolean;
    createdTs: string;
    updatedTs: string;
}

export interface PersonInterface {
    _id: string;
    user: string;
    name: string;
    email?: string;
    phone?: string;
    /**
     * Google Calendar "other person's calendar" ID, used for scheduling meetings with them.
     */
    externalCalendarId?: string;
    notes?: string;
    createdTs: string;
    updatedTs: string;
}

export interface WorkContextInterface {
    _id: string;
    user: string;
    /**
     * Human-readable label, e.g. "near a phone", "at work", "with family", "focused at laptop".
     */
    name: string;
    createdTs: string;
    updatedTs: string;
}

export interface OperationInterface {
    _id: string; // server-generated UUID
    user: string;
    /**
     * Stable device UUID generated on first app launch. Identifies the originating device.
     */
    deviceId: string;
    ts: string; // ISO datetime — when the change was made on the device
    entityType: EntityType;
    entityId: string;
    opType: OpType;
    /**
     * Full entity state at the time of the operation. null for delete operations.
     * Stored to allow any device to reconstruct state by replaying operations in ts order.
     */
    snapshot: ItemInterface | RoutineInterface | PersonInterface | WorkContextInterface | null;
}

export interface DeviceSyncStateInterface {
    /**
     * Stable device UUID (client-generated on first launch). Used as the document _id.
     */
    _id: string;
    user: string;
    /**
     * ISO datetime of the most recent operation this device has pulled from the server.
     * Operations older than the minimum lastSyncedTs across all devices for a user can be purged.
     */
    lastSyncedTs: string;
    /**
     * ISO datetime of the most recent operation this device has pushed to the server.
     */
    lastSeenTs: string;
    name?: string; // user-given label, e.g. "iPhone", "Work laptop"
}

export interface PushSubscriptionRecord {
    _id: string; // deviceId — one record per device, so upsert by deviceId keeps it current
    user: string;
    endpoint: string;
    keys: { p256dh: string; auth: string };
    updatedTs: string;
}

export interface CalendarIntegrationInterface {
    _id: string;
    user: string;
    provider: 'google'; // extensible: 'apple' | 'microsoft' in future
    accessToken: string; // OAuth access token — must be encrypted at rest
    refreshToken: string; // OAuth refresh token — must be encrypted at rest
    tokenExpiry: string; // ISO datetime
    calendarId: string; // Google Calendar ID to sync against
    lastSyncedTs?: string; // ISO datetime of last successful pull from this calendar
    createdTs: string;
    updatedTs: string;
}
