export const ItemStatus = {
    inbox: 'inbox',
    nextAction: 'nextAction',
    calendar: 'calendar',
    waitingFor: 'waitingFor',
    somedayMaybe: 'somedayMaybe',
    done: 'done',
    trash: 'trash',
} as const;
export type ItemStatus = (typeof ItemStatus)[keyof typeof ItemStatus];

export type EnergyLevel = 'low' | 'medium' | 'high';
export type EntityType = 'item' | 'routine' | 'person' | 'workContext';
export type OpType = 'create' | 'update' | 'delete';

export interface ItemInterface {
    /**
     * Client-generated UUID used as the MongoDB _id. Optional so MongoDB accepts documents created without one (e.g. in tests) but always present in practice.
     */
    _id?: string;
    user: string; // Better Auth user ID (UUID string, not ObjectId)
    status: ItemStatus;
    title: string;
    createdTs: string; // ISO datetime
    updatedTs: string; // ISO datetime — used as the conflict-resolution anchor (last write wins)
    /**
     * Refs to WorkContextInterface._id. Relevant for `nextAction` items.
     */
    workContextIds?: string[];
    /**
     * Refs to PersonInterface._id. Relevant for `nextAction` and `waitingFor` items.
     */
    peopleIds?: string[];
    /**
     * Ref to PersonInterface._id. The specific person being waited on (`waitingFor` items only).
     */
    waitingForPersonId?: string;
    /**
     * Deadline date (one-day resolution, ISO date string). Relevant for `nextAction` and `waitingFor` items.
     */
    expectedBy?: string;
    /**
     * Tickler date (ISO date string). Item is hidden from all lists until this date passes.
     * Only applies to `nextAction` and `waitingFor` items — `calendar` items ignore this field.
     * Separate from `timeStart` to avoid overloading.
     */
    ignoreBefore?: string;
    /**
     * Calendar event start datetime (ISO datetime string). `calendar` items only.
     */
    timeStart?: string;
    /**
     * Calendar event end datetime (ISO datetime string). `calendar` items only.
     */
    timeEnd?: string;
    /**
     * External calendar event ID (e.g. Google Calendar event ID). Set when this item is synced to a calendar.
     */
    calendarEventId?: string;
    /**
     * Ref to CalendarIntegrationInterface._id. Identifies which calendar integration owns the synced event.
     */
    calendarIntegrationId?: string;
    /**
     * Ref to CalendarSyncConfigInterface._id. Tracks which specific calendar within the integration this event belongs to.
     */
    calendarSyncConfigId?: string;
    /**
     * ISO datetime — set when the app pushes an edit to Google Calendar.
     * Used to detect and skip our own echo when a webhook-triggered pull finds the same change.
     */
    lastPushedToGCalTs?: string;
    /**
     * Ref to RoutineInterface._id. Set when this item was generated by a routine.
     */
    routineId?: string;
    energy?: EnergyLevel; // relevant for `nextAction` items
    time?: number; // estimated duration in minutes — relevant for `nextAction` items
    focus?: boolean; // requires uninterrupted focus — relevant for `nextAction` items
    urgent?: boolean; // must be done very soon — relevant for `nextAction` items
    notes?: string; // freeform markdown notes — applies to all statuses
    /**
     * The last notes value successfully synced from/to Google Calendar.
     * Used to detect whether Google's description changed since the last inbound sync,
     * enabling last-write-wins conflict resolution only when GCal actually changed it.
     */
    lastSyncedNotes?: string;
}

export interface RoutineItemTemplate {
    workContextIds?: string[];
    peopleIds?: string[];
    energy?: EnergyLevel;
    time?: number; // estimated minutes
    focus?: boolean;
    urgent?: boolean;
    notes?: string;
}

export interface RoutineInterface {
    _id: string;
    user: string;
    title: string;
    /**
     * nextAction: next instance created after previous is done/trashed (all frequencies are after-completion).
     * calendar: next instance created on a fixed rrule schedule.
     */
    routineType: 'nextAction' | 'calendar';
    /**
     * RFC 5545 RRULE string (e.g. FREQ=WEEKLY;BYDAY=MO). Required for all routines.
     * For nextAction routines, DTSTART is set dynamically to the completion date when computing the next occurrence.
     * For calendar routines, DTSTART is the routine's creation date (fixed absolute schedule).
     */
    rrule: string;
    /**
     * @deprecated Use routineType instead.
     */
    triggerMode?: 'afterCompletion' | 'fixedSchedule';
    /**
     * @deprecated Use rrule instead.
     */
    afterCompletionDelayDays?: number;
    /**
     * Google Calendar recurring event series ID. Set when the routine is linked to a calendar series.
     */
    calendarEventId?: string;
    /**
     * Ref to CalendarIntegrationInterface._id. Identifies which calendar integration owns the series.
     */
    calendarIntegrationId?: string;
    /**
     * Ref to CalendarSyncConfigInterface._id. Tracks which specific calendar within the integration this routine is linked to.
     */
    calendarSyncConfigId?: string;
    /**
     * Ref to the routine this was split from via a "this and all following" edit.
     * Set on the new tail routine; points back to the original (head) routine.
     */
    splitFromRoutineId?: string;
    /**
     * ISO datetime — set when the app pushes an edit to Google Calendar.
     * Used to detect and skip our own echo when a webhook-triggered pull finds the same change.
     */
    lastPushedToGCalTs?: string;
    /**
     * The last template.notes value successfully synced from/to Google Calendar.
     * See ItemInterface.lastSyncedNotes for full semantics.
     */
    lastSyncedNotes?: string;
    /**
     * Fields copied onto each item instance generated by this routine.
     */
    template: RoutineItemTemplate;
    active: boolean;
    createdTs: string;
    updatedTs: string;
    /**
     * ISO date (YYYY-MM-DD) — anchors the rrule schedule. Falls back to createdTs when unset.
     * User-editable in the routine edit dialog. For calendar routines, becomes the GCal series DTSTART
     * (snapped forward to the first BYDAY/BYMONTHDAY match by seriesStartDate). For nextAction routines,
     * no items are generated with an occurrence date before startDate.
     */
    startDate?: string;
    /**
     * Present when routineType === 'calendar'. Defines time and duration for generated calendar items.
     */
    calendarItemTemplate?: {
        timeOfDay: string; // HH:MM (24h) — start time
        duration: number; // minutes
    };
    /**
     * ISO date string of the most recently generated calendar item's date.
     * Used to compute the next occurrence without scanning items.
     */
    lastGeneratedDate?: string;
    /**
     * Exception records: dates in the rrule series that have been overridden or deleted.
     * When a user trashes a future calendar item, its date is recorded here as 'skipped'
     * so the next-item generator skips that occurrence.
     */
    routineExceptions?: Array<{
        date: string; // ISO date of the original rrule occurrence
        type: 'skipped' | 'modified';
        itemId?: string;
        newTimeStart?: string; // ISO datetime — present when type === 'modified'
        newTimeEnd?: string;
        title?: string; // overridden title — present when GCal instance title differs from master
        notes?: string; // overridden description — present when GCal instance description differs from master
    }>;
}

export interface PersonInterface {
    _id: string;
    user: string;
    name: string;
    email?: string;
    phone?: string;
    /**
     * Google Calendar "other person's calendar" ID, used for scheduling meetings with them.
     */
    externalCalendarId?: string;
    notes?: string;
    createdTs: string;
    updatedTs: string;
}

export interface WorkContextInterface {
    _id: string;
    user: string;
    /**
     * Human-readable label, e.g. "near a phone", "at work", "with family", "focused at laptop".
     */
    name: string;
    createdTs: string;
    updatedTs: string;
}

export interface OperationInterface {
    _id: string; // server-generated UUID
    user: string;
    /**
     * Stable device UUID generated on first app launch. Identifies the originating device.
     */
    deviceId: string;
    ts: string; // ISO datetime — when the change was made on the device
    entityType: EntityType;
    entityId: string;
    opType: OpType;
    /**
     * Full entity state at the time of the operation. null for delete operations.
     * Stored to allow any device to reconstruct state by replaying operations in ts order.
     */
    snapshot: ItemInterface | RoutineInterface | PersonInterface | WorkContextInterface | null;
}

export interface DeviceSyncStateInterface {
    /**
     * Composite id `${deviceId}::${userId}`. One row per (device, user) pair so two
     * Better Auth sessions on the same device each track their own pull cursor — a
     * single shared cursor would let one user's pull advance past the other user's
     * boundary op (the bug fixed by per-user cursors).
     */
    _id: string;
    /**
     * Stable device UUID (client-generated on first launch). Duplicated as a queryable
     * field so device-scoped operations (stale-device cleanup, push-subscription
     * removal) can scan by deviceId without parsing `_id`.
     */
    deviceId: string;
    user: string;
    /**
     * ISO datetime of the most recent operation this (device, user) pair has pulled
     * from the server. Operations older than the minimum lastSyncedTs across all
     * (device, user) rows for a user can be purged.
     */
    lastSyncedTs: string;
    /**
     * ISO datetime of the most recent operation this (device, user) pair has pushed
     * to the server.
     */
    lastSeenTs: string;
    name?: string; // user-given label, e.g. "iPhone", "Work laptop"
}

/**
 * Compose the deviceSyncState document _id from a (deviceId, userId) pair.
 * Invariant: neither deviceId nor userId may contain `::` — UUIDs (deviceIds) and Better Auth
 * user IDs never do, but we throw defensively so a future ID-format change can't silently
 * corrupt the legacy-row detection in `migrateDeviceSyncStateToPerUserCursor`.
 */
export function deviceSyncStateId(deviceId: string, userId: string): string {
    if (deviceId.includes('::') || userId.includes('::')) {
        throw new Error(`deviceSyncStateId: '::' is reserved as the deviceId/userId separator (deviceId=${deviceId}, userId=${userId})`);
    }
    return `${deviceId}::${userId}`;
}

export interface PushSubscriptionRecord {
    _id: string; // deviceId — one record per device, so upsert by deviceId keeps it current
    /**
     * Better Auth user ID of the account that registered the subscription.
     * Informational only: a single device may host several logged-in accounts; reads of
     * "which devices to push to for user X" go through `deviceUsers` joined on `deviceId`.
     */
    user: string;
    endpoint: string;
    keys: { p256dh: string; auth: string };
    updatedTs: string;
}

/**
 * Join row recording every (device, user) pair the device currently hosts a Better Auth session for.
 * Maintained by the auth middleware on every authenticated request and removed on signOut /
 * push subscription expiry.
 */
export interface DeviceUserInterface {
    /** Composite key `<deviceId>:<userId>` — one row per (device, user) pair. */
    _id: string;
    deviceId: string;
    userId: string;
    createdTs: string; // ISO datetime — first time this device announced this user
    lastSeenTs: string; // ISO datetime — most recent authenticated request from this device for this user
}

export interface CalendarIntegrationInterface {
    _id: string;
    user: string;
    provider: 'google'; // extensible: 'apple' | 'microsoft' in future
    accessToken: string; // OAuth access token — must be encrypted at rest
    refreshToken: string; // OAuth refresh token — must be encrypted at rest
    tokenExpiry: string; // ISO datetime
    /**
     * @deprecated Per-calendar sync state moved to `CalendarSyncConfigInterface` (one config row per
     * synced calendar). New integrations no longer write this field; legacy rows keep it for lazy
     * migration in `ensureSyncConfigExists`. New code paths must read sync configs instead.
     */
    calendarId?: string;
    lastSyncedTs?: string; // ISO datetime of last successful pull from this calendar
    /**
     * OAuth auth state. Absent ⇒ treated as `'active'`. Lifecycle:
     *  - `'active'`: tokens believed valid; sync + pushback proceed normally.
     *  - `'suspended'`: a refresh attempt failed with `invalid_grant`; warning email sent. Sync still
     *     attempts (the failure may have been transient); after 24h elapsed since `suspendedAt` the
     *     escalation flips status to `'revoked'`.
     *  - `'revoked'`: soft-deleted. Sync/pushback skip; sync endpoint returns HTTP 410. Reconnect via
     *     OAuth (`upsertEncrypted`) clears status back to `'active'`.
     */
    status?: 'active' | 'suspended' | 'revoked';
    suspendedAt?: string; // ISO datetime — set when first invalid_grant detected
    revokedAt?: string; // ISO datetime — set when 24h grace expires
    lastAuthErrorAt?: string; // ISO datetime — bumped on every invalid_grant occurrence
    createdTs: string;
    updatedTs: string;
}

/**
 * Audit row for outbound emails. The current `sendEmail` implementation is a stub that logs and
 * persists this row; a real email provider replaces the body of `sendEmail` while preserving this
 * audit log so prior sends remain queryable.
 */
export interface SentEmailInterface {
    _id: string;
    userId: string;
    to: string;
    subject: string;
    body: string;
    kind: 'calendar_auth_warning' | 'calendar_auth_revoked';
    sentAt: string;
}

export interface CalendarSyncConfigInterface {
    _id: string;
    /** Ref to CalendarIntegrationInterface._id — the OAuth integration this calendar belongs to. */
    integrationId: string;
    user: string;
    /** Google Calendar ID (e.g. 'primary', 'work@group.calendar.google.com'). */
    calendarId: string;
    /** Human-readable calendar name from Google (e.g. "Work", "Holidays"). */
    displayName?: string;
    /** When true, new app-created calendar items default to this calendar. Only one config per integration may be default. */
    isDefault: boolean;
    /** User can pause sync for individual calendars without removing them. */
    enabled: boolean;
    /** ISO datetime of last successful pull from this specific calendar. */
    lastSyncedTs?: string;
    /** Google incremental sync token — used to fetch only changed events since last sync. */
    syncToken?: string;
    /** UUID for the Google Calendar push notification channel. */
    webhookChannelId?: string;
    /** Google's resource ID for the active watch. Paired with webhookChannelId for verification. */
    webhookResourceId?: string;
    /** ISO datetime when the webhook channel expires and must be renewed. */
    webhookExpiry?: string;
    /** IANA timezone of this calendar (e.g. "Asia/Jerusalem"). Fetched from Google, refreshed on sync. */
    timeZone?: string;
    createdTs: string;
    updatedTs: string;
}

/** Union of all entity types that can appear as an operation snapshot. */
export type EntitySnapshot = ItemInterface | RoutineInterface | PersonInterface | WorkContextInterface;
